export interface Item {
    id: number;
    name: string;
    description: string;
    oldamount: string;
    newamount: string;
    imageUrl: string;
    rating: number;
    reviewsCount: number;
  }
  
  export const items: Item[] = [
    {
      id: 1,
      name: "Sausage Rolls",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "sausage-rolls.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 2,
      name: "Cinnamon Rolls",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "cinnamon-rolls.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 3,
      name: "Buns with Raisins",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "buns-with-raisins.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 4,
      name: "Glazed Doughnut",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "glazed-doughnut.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 5,
      name: "Spring Rolls",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "spring-rolls.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 6,
      name: "Iced Doughnut",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "iced-doughnut.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 7,
      name: "Raisin Bread",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "raisin-bread.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 8,
      name: "Doughnuts",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "doughtnuts.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 9,
      name: "Butter Cookies",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "butter-cookies.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 10,
      name: "Croissant",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "croissant.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 11,
      name: "Cinnamon Rolls",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "cinnamon-rolls.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 12,
      name: "Glazed Doughnut",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "glazed-doughnut.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 10,
      name: "Croissant",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "croissant.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 14,
      name: "Cinnamon Rolls",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "cinnamon-rolls.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 15,
      name: "Glazed Doughnut",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "glazed-doughnut.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 16,
      name: "Glazed Doughnut",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "doughnut.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 17,
      name: "Glazed Doughnut",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "doughnut.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 18,
      name: "Glazed Doughnut",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "doughnut.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 19,
      name: "Glazed Doughnut",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "doughnut.png",
      rating: 1,
      reviewsCount: 4,
    },
    {
      id: 20,
      name: "Glazed Doughnut",
      description: "Enjoy our tasty, mouth watering sausage rolls",
      oldamount: "N350.00",
      newamount: "₦250.00",
      imageUrl: "doughnut.png",
      rating: 1,
      reviewsCount: 4,
    },
   
  ];