export interface Item {
  id: number;
  name: string;
  description: string;
  oldamount: string;
  newamount: string;
  imageUrl: string;
  rating: number;
  reviewsCount: number;
}

export const items: Item[] = [
  {
    id: 1,
    name: "Sausage Rolls",
    description: "Enjoy our tasty, mouth watering sausage rolls",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausage-roll.png",
    rating: 1,
    reviewsCount: 5,
  },
  {
    id: 2,
    name: "Cinnamon Rolls",
    description: "Enjoy our tasty, mouth watering sausage rolls",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "cinnamon-rolls.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 3,
    name: "Buns with Raisins",
    description: "Enjoy our tasty, mouth watering sausage rolls",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "Buns-with-Raisins.png",
    rating: 1,
    reviewsCount: 5,
  },
  {
    id: 4,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 5,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 6,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 7,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 8,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 9,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 10,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 11,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 12,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 13,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 14,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 15,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 16,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 17,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 18,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 19,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 20,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 21,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 22,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 23,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 24,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 25,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 26,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 27,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
  {
    id: 28,
    name: "Glazed Doughnut",
    description: "Enjoy our tasty, mouth watering",
    oldamount: "N350.00",
    newamount: "₦250.00",
    imageUrl: "sausages-dough-isolated.png",
    rating: 1,
    reviewsCount: 4,
  },
];
